# Generated by Django 5.2.3 on 2025-08-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodTimetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        default="Monday",
                        max_length=9,
                        unique=True,
                    ),
                ),
                ("break_fast", models.CharField(default="", max_length=10)),
                ("lunch", models.CharField(default="", max_length=200)),
                ("snacks", models.CharField(default="", max_length=200)),
                ("dinner", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
